### ISSUE TITLE
air sdk 50.2.2.3 android app crash

### ISSUE THREAD

**Issue by mehmury** [airsdk/Adobe-Runtime-Support#2568]
I wanted to make a new update with the air sdk 50.2.2.3 version for an application in google play store. In the application, there are firebase analytics, permisioncheck anes of old myflashlabs. And there are admob advertisement plugin and idfa plugin belonging to distriqt.
In previous air sdk versions, I was using these old and new anes together on the android side and there was no problem. In the latest air sdk version, my application crashed.
I updated the latest versions of distriqt's moments, my app started crashing constantly on android devices. I went to do internal testing on Google Play Console and they sent the below crash report to my e-mail address. It was an application that worked smoothly with previous SDKs. Could it be that the new version SDKs do not support the old ace encoding?

GOOGLE PLAY CONSOLE İNTERNAL TEST CRASH REPORTS BELOW
Crashes

Devices with issues
7

Device(s) with issues
Google Pixel 7 (panther) - Android 13
Google Pixel 6 (oriole) - Android 12
Google Pixel 5 (redfin) - Android 11
Samsung SM-G981U1 (x1q) - Android 10
Google Pixel 2 (Pixel2Emulator) - Android 12
Google Pixel 2 (Pixel2Emulator) - Android 13
Google Pixel 2 (Pixel2Emulator) - Android 9

Exceptions
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/base.apk", zip file "/data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.arm64_v8a.apk", zip file "/data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.tr.apk", zip file "/data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/lib/arm64, /data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/base.apk!/lib/arm64-v8a, /data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.tr.apk!/lib/arm64-v8a, /data/app/~~wn6E1W7NpRF4ltPnr68Wbg==/air.testandrocam-PrsdoZMYuXasUowKyX_1TQ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/base.apk", zip file "/data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.arm64_v8a.apk", zip file "/data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.az.apk", zip file "/data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/lib/arm64, /data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/base.apk!/lib/arm64-v8a, /data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.az.apk!/lib/arm64-v8a, /data/app/~~iRsETq1SDnVGmLUs156hWQ==/air.testandrocam-zgUxBAzN49Pe6FNBRAXhsg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/base.apk", zip file "/data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.arm64_v8a.apk", zip file "/data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.en.apk", zip file "/data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/lib/arm64, /data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/base.apk!/lib/arm64-v8a, /data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~6UaEs_dsqddfK10FFDcmuQ==/air.testandrocam-rN7V4ouJXRzaRf94v1MPYg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/lib/arm64, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/lib/arm64, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/lib/arm64, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk", zip file "/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/lib/arm64, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/base.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.tr.apk!/lib/arm64-v8a, /data/app/air.testandrocam-E3AHXGe7KVof3MDbghP-ZQ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/base.apk", zip file "/data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.az.apk", zip file "/data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.x86_64.apk", zip file "/data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/lib/x86_64, /data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/base.apk!/lib/x86_64, /data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.az.apk!/lib/x86_64, /data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.x86_64.apk!/lib/x86_64, /data/app/~~E9rIotAb1gC6XuWoWaoZfQ==/air.testandrocam-qNV0x_cBzNqZS19WyeBE1g==/split_config.xxhdpi.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/base.apk", zip file "/data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.en.apk", zip file "/data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.x86_64.apk", zip file "/data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/lib/x86_64, /data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/base.apk!/lib/x86_64, /data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.en.apk!/lib/x86_64, /data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.x86_64.apk!/lib/x86_64, /data/app/~~SbUumeE7ucKt8_kc8gzA_g==/air.testandrocam-ZwEJltAruUY9M58q_xAUgA==/split_config.xxhdpi.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/base.apk", zip file "/data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.tr.apk", zip file "/data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.x86.apk", zip file "/data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/lib/x86, /data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/base.apk!/lib/x86, /data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.tr.apk!/lib/x86, /data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.x86.apk!/lib/x86, /data/app/air.testandrocam-hSnw81pPH9JLCG4XonsnVQ==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]

**Comment by ajwfrost** [comment]
Hi

Can I check what you mean by "in previous air sdk versions"? Is there a version where it was working?
And can you also confirm whether you've changed the namespace in your application descriptor file, and what value it has?

There are some odd behaviours we've seen with applications working differently depending on whether they're built using the older Android build tools (which is how ADT used to package up APK files) vs the newer build tools (using Gradle, which is how ADT creates AAB files and - as long as your namespace is high enough and you have the tools - for APK too).

If you can check the output of the ADT debug log file for the old and new cases, this may show up a difference..

thanks

   Andrew

**Comment by mehmury** [comment]
in my apps main xml namespace
<application xmlns="http://ns.adobe.com/air/application/50.2">

my app work with air sdk 50.2.2.1 android devices.

I'm just testing my app with the new air sdk. i think in august 2023 google will ask for api level 33 in new updates. i want to be ready for that time. actually i don't need an urgent update right now.

**Comment by ajwfrost** [comment]
Okay that's very odd, if it worked with 50.2.2.1 and is failing with 50.2.2.3... especially if it's related to a Java 'class not found' which implies a problem with the multidex thing - there shouldn't be any differences between those two releases that would impact this. Unless somehow ADT is switching between 'old' and 'new' build mechanisms, but the logic is the same in both those releases..

The update to API 33 is something we're working on but will come a after we've resolved the current filesystem access problems..

thanks

**Comment by mehmury** [comment]
> Okay that's very odd, if it worked with 50.2.2.1 and is failing with 50.2.2.3... especially if it's related to a Java 'class not found' which implies a problem with the multidex thing - there shouldn't be any differences between those two releases that would impact this. Unless somehow ADT is switching between 'old' and 'new' build mechanisms, but the logic is the same in both those releases..
> 
> The update to API 33 is something we're working on but will come a after we've resolved the current filesystem access problems..
> 
> thanks

thanks.
I got the adt.log file during compiling with air sdk 50.2.2.3. I am attaching the outputs.
I can't get adt.log output in compiling with air sdk 50.2.1.1. There is a problem in logging in that version.
in the last commit I defined the path of java jdk-20 version in adt config as JAVA_HOME link.
The result did not change even when I changed the java version to the current version. The application is packaged without any problems, but when it is installed on the device, the application crashes.
By the way, I'm compiling with Adobe Animate.
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/11147094/adt.log)

**Comment by mehmury** [comment]
I created a new compiling for my same application with air sdk 50.2.2.3. This time I wanted to test the application on the android device by making the package as classic apk with adobe animate and got the adt.log records.
My app crashes on android device even when it is created as apk.

I am attaching the adt.log file
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/11147757/adt.log)

**Comment by amorganiv** [comment]
Also, had our APK crash on startup using AIR 50.2.2.3. Seems to fail when attempting to connect to the internet. The APK built with AIR 50.2.2.1 started correctly without any issues.

Here is the output from Android Studio:
[log-startup-50.2.2.3.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/11153950/log-startup-50.2.2.3.txt)
[log-startup-50.2.2.1.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/11153951/log-startup-50.2.2.1.txt)

**Comment by ajwfrost** [comment]
Thanks .. both these are very strange-sounding issues, in areas that should not have changed at all. The one thing that did change with 50.2.2.3 was that we had to swap out a build server, but all the tools/environment etc should be all captured and the same on both machines.. but I will check that again and see if there's any way we can resurrect the old machine..

**Comment by marchbold** [comment]
FYI we are seeing some weird issues with 50.2.2.3 too, I'll try to grab some logs when i get a chance but we rolled back to 50.2.2.2 currently.

**Comment by itlancer** [comment]
We also get crashes with some Android devices using AIR 50.2.2.3. "class not found' and related.
Some logs:
```
AdobeAIR: Unable to load AIR file utils - content URIs will be unavailable
System.err: java.lang.ClassNotFoundException: Didn't find class "com.adobe.air.AIRFileUtils" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/lib64]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
AdobeAIR: Unable to load AIR file utils - content URIs will be unavailable
my.app: thread.cc:2148] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "com.adobe.air.AIRFileUtils" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/lib64]]
my.app: thread.cc:2148]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
my.app: thread.cc:2148]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
my.app: thread.cc:2148]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
```

**Comment by nanhuichen** [comment]
We also get crashes on Google Pixel 2 (virtual), x86 and x86_64

backtrace:
  #00  pc 0x0000000000348b49  /data/app/~~tQsUzEeOMq2qrPzb91p80w==/com.lowolf.creepyslots-CBoefOv0fcLERo9TDVdNIA==/split_config.x86_64.apk!libCore.so
  #01  pc 0x000000000075df62  /data/app/~~tQsUzEeOMq2qrPzb91p80w==/com.lowolf.creepyslots-CBoefOv0fcLERo9TDVdNIA==/split_config.x86_64.apk!libCore.so
  #02  pc 0x000000000075607d  /data/app/~~tQsUzEeOMq2qrPzb91p80w==/com.lowolf.creepyslots-CBoefOv0fcLERo9TDVdNIA==/split_config.x86_64.apk!libCore.so
  #03  pc 0x000000000000d8f4 

backtrace:
  #00  pc 0x00000000001a517a  /data/app/com.lowolf.creepyslots-Zh2ulo2nk3t5E_4u9mJtZg==/split_config.x86.apk
  #01  pc 0x0000000000667f2b  /data/app/com.lowolf.creepyslots-Zh2ulo2nk3t5E_4u9mJtZg==/split_config.x86.apk
  #02  pc 0x000000000065edcd  /data/app/com.lowolf.creepyslots-Zh2ulo2nk3t5E_4u9mJtZg==/split_config.x86.apk
  #03  pc 0x00000000007051fb  /data/app/com.lowolf.creepyslots-Zh2ulo2nk3t5E_4u9mJtZg==/split_config.x86.apk
  #04  pc 0x00000000007052ad  /data/app/com.lowolf.creepyslots-Zh2ulo2nk3t5E_4u9mJtZg==/split_config.x86.apk
  #05  pc 0x00000000000031ed

**Comment by mehmury** [comment]
For the new version of my application that I opened the topic of, I was able to revert to the air sdk 50.1.1.1 version and make a suitable compiling with the old and new moments in the content.
No crashes reported in Google launch reporting. Changes to 50.2.x.x are causing my app to not work properly.

I tried the 50.2.x.x versions one after the other. Crashes were reported on some devices. I went back to 50.1.1.1 and updated it without any problems.

**Comment by Policy56** [comment]
Got same error in 5.2.2.3, any update ?

**Comment by itlancer** [comment]
For me it fixed with AIR 50.2.2.4.

**Comment by mehmury** [comment]
Problem solved with air sdk 50.2.2.4. My application is running smoothly.
Thanks.

**Comment by nanhuichen** [comment]
After update SDK to 50.2.2.4, we still see the crash report on x86 devices.

<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="33"/>

![image](https://user-images.githubusercontent.com/13010645/232224111-68f0b263-d68a-47ca-9a6c-dacaf26fe57f.png)

**Comment by nanhuichen** [comment]
> 

after I replace a older ANE, it seems work fine now.
