### ISSUE TITLE
SDK 51.1.2.1-51.1.3.1 ANE at AndroidActivityWrapper_nativeSetVisible

### ISSUE THREAD

**Issue by bobrokrol** [airsdk/Adobe-Runtime-Support#3595]
So it started appearing in console after AIR 51.1.2.1 update and happens with all sdk's including latest  AIR 51.1.3.1

[split_config.arm64_v8a.apk!libCore.so] Java_com_adobe_air_AndroidActivityWrapper_nativeSetVisible
[stacktrace.log (1).txt](https://github.com/user-attachments/files/18050368/stacktrace.log.1.txt)

**Comment by ajwfrost** [comment]
Below is a patch to replace the AIRSDK/lib/android/lib/runtimeClasses.jar file
[runtimeClasses_3595.zip](https://github.com/user-attachments/files/18063242/runtimeClasses_3595.zip)

**Comment by bobrokrol** [comment]
> Below is a patch to replace the AIRSDK/lib/android/lib/runtimeClasses.jar file [runtimeClasses_3595.zip](https://github.com/user-attachments/files/18063242/runtimeClasses_3595.zip)

ok, thank you.

**Comment by bobrokrol** [comment]
> Thanks for the report and stack trace.
> 
> We're slowly working through a number of these kinds of issues, and it seems that when we resolve some of them, it then exposes different ones... This one is fairly straightforward to fix but as soon as you see other ANR reports like this, please let us know!
> 
> thanks

many of them was fixed in the latest release, good job!

**Comment by lwmirkk** [comment]
@ajwfrost Starting AIR SDK 51, I receiving a lot of this ANR on Google Console:

**android.app.ActivityThread$H.handleMessage**
```

Exception android.app.RemoteServiceException:
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1738)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6680)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

I still can't track down the cause of this problem, but it started with SDK version 51 and persists until the most recent updates. I didn't test whether the file you attached here would solve the problem.

However, the stack trace I have is only this small one from the Console, and since I haven't been able to see the problem happening nearby, I couldn't get a deeper stack trace. With this stack trace, can you get an idea of ​​what it might be?

Thanks a lot!

**Comment by ajwfrost** [comment]
Hi @lwmirkk  - this doesn't really give us much information! From this it doesn't look like an ANR even, it's just showing an exception happening within a message handler; I'm doubtful whether it's even showing details for the right process since there's no mention of AIR in there (we have custom looper and event handler classes that I would expect to see there..). Are there no other reports in the console that provide a different call stack with the state of multiple threads shown there?

Are you using the `runtimeInBackgroundThread` flag? This was intended to reduce the ANRs caused by slow application activity, but has raised it's own set of ANRs caused by synchronisation issues between the UI elements and the AIR runtime... it may be worth toggling this setting and seeing if anything changes perhaps?

thanks
